version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      API_BASE_URL: http://api:8000/
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      INCORRECT_BEARER_TOKEN: ${INCORRECT_BEARER_TOKEN}
    depends_on:
      - logserver

  logserver:
    build:
      context: .
      dockerfile: Dockerfile.logserver
    ports:
      - "9020:9020"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
      - logserver
    environment:
      API_BASE_URL: http://api:8000/
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      INCORRECT_BEARER_TOKEN: ${INCORRECT_BEARER_TOKEN}
    volumes:
      - ./allure-results:/app/allure-results
      - ./report:/app/report
      - ./automation.log:/app/automation.log
    command: >
      sh -c "
        pytest
      "
