name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI app (Uvicorn)
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          INCORRECT_BEARER_TOKEN: ${{ secrets.INCORRECT_BEARER_TOKEN }}
        run: |
          Start-Process python -ArgumentList '-m','uvicorn','main:app','--host','127.0.0.1','--port','8000'
          Start-Sleep -Seconds 10

      - name: Start log server
        run: |
          python utils/logs/log_server.py &
          sleep 2
        shell: bash

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          INCORRECT_BEARER_TOKEN: ${{ secrets.INCORRECT_BEARER_TOKEN }}
        run: |
          pytest

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload pytest-html report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report/

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-log
          path: automation.log