name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI app (Uvicorn)
        env:
          API_BASE_URL: http://127.0.0.1:8000/
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          INCORRECT_BEARER_TOKEN: ${{ secrets.INCORRECT_BEARER_TOKEN }}
        run: |
          Start-Process python -ArgumentList '-m','uvicorn','app.main:app','--host','127.0.0.1','--port','8000'
          Start-Sleep -Seconds 10

      - name: Create admin account in DB
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run:
          python seed.py

      - name: Start log server
        run: |
          python testing/utils/logs/log_server.py &
          sleep 2
        shell: bash

      - name: Run tests
        env:
          API_BASE_URL: http://127.0.0.1:8000/
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          INCORRECT_BEARER_TOKEN: ${{ secrets.INCORRECT_BEARER_TOKEN }}
        run: |
          pytest

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload pytest-html report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report/

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-log
          path: automation.log

      - name: Send Telegram notification on success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d text="✅ Tests PASSED for *${{ github.repository }}*\n🔁 Commit: `${{ github.sha }}`" \
            -d parse_mode=Markdown

      - name: Send Telegram notification on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d text="❌ Tests FAILED for *${{ github.repository }}*\n🔁 Commit: `${{ github.sha }}`" \
            -d parse_mode=Markdown